# Generated by Django 3.2 on 2025-04-08 06:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import user_management.helpers
import user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('CA', 'Chartered Accountant Firm'), ('Business', 'Business/Corporate'), ('ServiceProvider', 'ServiceProvider')], default=None, max_length=40, null=True)),
                ('service_request', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nameOfBusiness', models.CharField(db_index=True, max_length=200, unique=True)),
                ('registrationNumber', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('entityType', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('headOffice', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('pan', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('business_nature', models.CharField(blank=True, choices=[('Agency or Sales House', 'Agency or Sales House'), ('Agriculture', 'Agriculture'), ('Art and Design', 'Art and Design'), ('Automotive', 'Automotive'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Consumer Packaged Goods', 'Consumer Packaged Goods'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Financial Services', 'Financial Services'), ('Food Services (Restaurants/Fast Food)', 'Food Services (Restaurants/Fast Food)'), ('Gaming', 'Gaming'), ('Government', 'Government'), ('Health Care', 'Health Care'), ('Interior Design', 'Interior Design'), ('Internal', 'Internal'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Mining and Logistics', 'Mining and Logistics'), ('Non-Profit', 'Non-Profit'), ('Publishing and Web Media', 'Publishing and Web Media'), ('Real Estate', 'Real Estate'), ('Retail (E-Commerce and Offline)', 'Retail (E-Commerce and Offline)'), ('Services', 'Services'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Travel/Hospitality', 'Travel/Hospitality'), ('Web Designing', 'Web Designing'), ('Web Development', 'Web Development'), ('Writers', 'Writers')], default=None, max_length=50, null=True)),
                ('trade_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('dob_or_incorp_date', models.DateField(blank=True, default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_clients_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nameOfBusiness', 'pan')},
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number with 10-15 digits, optionally starting with +', regex='^\\+?\\d{10,15}$')])),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number with 10-15 digits, optionally starting with +', regex='^\\+?\\d{10,15}$')])),
                ('message', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, unique=True)),
                ('module_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=15, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'purpose', 'visa_type', 'destination_country')},
            },
        ),
        migrations.CreateModel(
            name='UserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pan_number', user_management.models.EncryptedField(blank=True, max_length=20, null=True)),
                ('aadhaar_number', user_management.models.EncryptedField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('icai_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.JSONField(blank=True, default=dict, null=True)),
                ('have_firm', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userkyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAffiliationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_affiliated', djongo.models.fields.JSONField(blank=True, default=list)),
                ('ca_firm_affiliated', djongo.models.fields.JSONField(blank=True, default=list)),
                ('service_provider_affiliated', djongo.models.fields.JSONField(blank=True, default=list)),
                ('business_affiliated', djongo.models.fields.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAffiliatedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=False)),
                ('affiliated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
                ('custom_permissions', models.ManyToManyField(blank=True, help_text='User-specific custom permissions.', related_name='user_groups', to='user_management.CustomPermission')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='user_management.customgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('created', 'Created'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=40)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='user_management.servicesmasterdata')),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='user_management.visaapplications')),
            ],
        ),
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('gstin', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('gst_username', models.CharField(blank=True, max_length=60, null=True)),
                ('gst_password', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('pinCode', models.IntegerField(null=True)),
                ('branch_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('authorized_signatory_pan', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('gst_document', models.FileField(blank=True, null=True, upload_to=user_management.helpers.gst_document_upload_path)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='user_management.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirmKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_registration_number', models.CharField(blank=True, max_length=40, null=True)),
                ('firm_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('firm_mobile_number', models.CharField(blank=True, max_length=40, null=True)),
                ('number_of_firm_partners', models.IntegerField()),
                ('address', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(related_name='groups', to='user_management.CustomPermission'),
        ),
    ]
